# -*- coding: utf-8 -*-
"""03_handle_overfitting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IYW9s2PqRwsWgDOgapToqGp4yohJ-f3_
"""

# Import necessary libraries
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Flatten, Dense, Dropout
import tensorflow.keras as keras

# Build an improved model with dropout layers
enhanced_model = Sequential([
    Flatten(input_shape=(features.shape[1], features.shape[2])),
    Dense(512, activation='relu', kernel_regularizer=keras.regularizers.l2(0.001)),
    Dropout(0.3),
    Dense(256, activation='relu', kernel_regularizer=keras.regularizers.l2(0.003)),
    Dropout(0.3),
    Dense(64, activation='relu', kernel_regularizer=keras.regularizers.l2(0.01)),
    Dropout(0.3),
    Dense(32, activation='relu'),
    Dense(10, activation='softmax')
])

# Compile the enhanced model
enhanced_model.compile(optimizer='adam',
                       loss='sparse_categorical_crossentropy',
                       metrics=['accuracy'])

# Train the enhanced model
enhanced_model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=50, batch_size=32)